### ISSUE TITLE
Unexpected lockState 'unlatched' returned, setting to UNDEF

### ISSUE THREAD

**Issue by Firebird231** [seime/openhab-august#1]
Version: 4.1.0
Product: Yale Smart Door Lock with position (opened, closed) detection. (in addition  to locked/unlocked)

**Comment by seime** [comment]
Hi @Firebird231 , didn't notice your message.

Could you provide logs?

Also, do you agree that it makes sense to update to OFF instead?

**Comment by seime** [comment]
Now setting lockState to OFF if "unlatched" state received from API
