### ISSUE TITLE
Binding crashes when Cloudflair error returned

### ISSUE THREAD

**Issue by StealthCat** [seime/openhab-august#2]
Binding crashes and goes to "COMM_ERROR" state when it tries to reach the API but a CloudFlair error page is returned.

**Comment by seime** [comment]
This could be:
- Intermittent issue
- Too frequent polling causing it to block you
- Something else

I tested disabling/enabling the binding on my setup without any such errors.

To investigate further I would need logs on a DEBUG level that shows the network traffic. Make sure to remove anything sensitive. Also please post your configuration

**Comment by StealthCat** [comment]
I've lowered the polling time and set the logging to DEBUG, will update when it happens again.

**Comment by StealthCat** [comment]
This corrected the issue
